# Generated by Django 4.2.7 on 2023-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('EXPRESSO', 'Café Expresso'), ('CAPPUCCINO', 'Cappuccino'), ('ROBUSTA', 'Café Robusta'), ('EXTRAFORTE', 'Café Extra Forte')], default='', max_length=100),
        ),
    ]
