# Generated by Django 4.2.7 on 2023-11-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('EXPRESSO', 'Café Expresso'), ('CAPPUCCINO', 'Cappuccino'), ('ROBUSTA', 'Café Robusta'), ('EXTRAFORTE', 'Café Extra Forte'), ('COMIDA', 'Refeições')], default='', max_length=100),
        ),
    ]
