# Generated by Django 4.2.7 on 2023-11-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
