# Generated by Django 4.2.7 on 2023-11-14 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_produto_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
