# Generated by Django 4.2.7 on 2023-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_produto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
