# Generated by Django 4.2.7 on 2023-11-14 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0009_alter_produto_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
