# Generated by Django 4.2.7 on 2023-12-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0011_alter_produto_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('QUENTE', 'Cafés quentes'), ('GELADO', 'Cafés Gelados'), ('CHA', 'Chás'), ('PADARIA', 'Padária'), ('REFEICAO', 'Refeições')], default='', max_length=100),
        ),
    ]
